### ISSUE TITLE
Todo before v1.0

### ISSUE THREAD

**Issue by OstlerDev** [oipwg/autominer-frontend#1]
- [ ] Implement JS loading of Logs
- [ ] Implement JS loading of Hashrates from API
- [ ] Implement Config saving/altering
- [ ] Implement Login page, store login details in session cookies
- [ ] Load spending history from DB
- [ ] Load Miners and Spent last week

**Comment by OstlerDev** [comment]
Closed temporarily
